### PR TITLE
Add BaGet news

### PR DESCRIPTION
**Pull request by loic-sharma**
Related to #25

### CODE REVIEW

**Comment by gep13** [comment]
@loic-Sharma apologies if I have missed something, but is BaGet now a .Net Foundation project? Is section of the newsletter is for updates to projects within the .Net Foundation.

@jongalloway @haacked What are our thoughts on a Community News section?

**Comment by loic-sharma** [comment]
BaGet is not a .NET Foundation project. From the newsletter’s readme:

> While we expect project maintainers to submit interesting news about their projects, we welcome anyone in the .NET community to submit news related to the Foundation or Foundation Projects

From my understanding, BaGet fits this description as it is related to a Foundation Project (NuGet). I apologize if my interpretation was incorrect!

**Comment by gep13** [comment]
>@loic-sharma said...
I apologize if my interpretation was incorrect!

Absolutely no need to apologize!  I am just trying to figure out `where` this news needs to go.  Currently, it is in the `.Net Foundation Project Updates` section, and I think we would need another section in the newsletter to accomodate it.

Let's wait and see what @jongalloway and @haacked have to say on the matter.

**Comment by haacked** [comment]
Maybe we should add a general .NET Ecosystem/Project news section for non-Foundation projects. @jongalloway @dotnet-foundation/directors thoughts?

**Comment by jongalloway** [comment]
I agree, this could bring in more community interest. **Community Project News** section?

**Comment by loic-sharma** [comment]
That sounds good to me. Would you like me to update my pull request?

**Pull request merged**
